name: solar
description: "A new Flutter project."
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  latlong2: ^0.9.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  animated_toggle_switch: ^0.8.5
  jwt_decoder: ^2.0.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  fl_chart: ^1.1.1
  intl: ^0.20.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  firebase_crashlytics: ^5.0.4
  firebase_analytics: ^12.0.4
  rive: ^0.14.0-dev.13

dependency_overrides:
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/solar_icon.png
    - assets/animations/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/solar_icon.png"
  remove_alpha_ios: true
